<?php

// Data functions (insert, update, delete, form) for table equipos

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function equipos_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('equipos');
	if(!$arrPerm[1]){
		return false;
	}

	$data['interno'] = makeSafe($_REQUEST['interno']);
		if($data['interno'] == empty_lookup_value){ $data['interno'] = ''; }
	$data['articulo'] = makeSafe($_REQUEST['articulo']);
		if($data['articulo'] == empty_lookup_value){ $data['articulo'] = ''; }
	$data['producto'] = br2nl(makeSafe($_REQUEST['producto']));
	$data['marca'] = makeSafe($_REQUEST['marca']);
		if($data['marca'] == empty_lookup_value){ $data['marca'] = ''; }
	$data['modelo'] = makeSafe($_REQUEST['modelo']);
		if($data['modelo'] == empty_lookup_value){ $data['modelo'] = ''; }
	$data['familia'] = makeSafe($_REQUEST['familia']);
		if($data['familia'] == empty_lookup_value){ $data['familia'] = ''; }
	$data['numero_serie'] = makeSafe($_REQUEST['numero_serie']);
		if($data['numero_serie'] == empty_lookup_value){ $data['numero_serie'] = ''; }
	$data['motor_marca'] = makeSafe($_REQUEST['motor_marca']);
		if($data['motor_marca'] == empty_lookup_value){ $data['motor_marca'] = ''; }
	$data['motor_modelo'] = makeSafe($_REQUEST['motor_modelo']);
		if($data['motor_modelo'] == empty_lookup_value){ $data['motor_modelo'] = ''; }
	$data['motor_serie'] = makeSafe($_REQUEST['motor_serie']);
		if($data['motor_serie'] == empty_lookup_value){ $data['motor_serie'] = ''; }

	// hook: equipos_before_insert
	if(function_exists('equipos_before_insert')){
		$args=array();
		if(!equipos_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `equipos` set       `interno`=' . (($data['interno'] !== '' && $data['interno'] !== NULL) ? "'{$data['interno']}'" : 'NULL') . ', `articulo`=' . (($data['articulo'] !== '' && $data['articulo'] !== NULL) ? "'{$data['articulo']}'" : 'NULL') . ', `producto`=' . (($data['producto'] !== '' && $data['producto'] !== NULL) ? "'{$data['producto']}'" : 'NULL') . ', `marca`=' . (($data['marca'] !== '' && $data['marca'] !== NULL) ? "'{$data['marca']}'" : 'NULL') . ', `modelo`=' . (($data['modelo'] !== '' && $data['modelo'] !== NULL) ? "'{$data['modelo']}'" : 'NULL') . ', `familia`=' . (($data['familia'] !== '' && $data['familia'] !== NULL) ? "'{$data['familia']}'" : 'NULL') . ', `numero_serie`=' . (($data['numero_serie'] !== '' && $data['numero_serie'] !== NULL) ? "'{$data['numero_serie']}'" : 'NULL') . ', `motor_marca`=' . (($data['motor_marca'] !== '' && $data['motor_marca'] !== NULL) ? "'{$data['motor_marca']}'" : 'NULL') . ', `motor_modelo`=' . (($data['motor_modelo'] !== '' && $data['motor_modelo'] !== NULL) ? "'{$data['motor_modelo']}'" : 'NULL') . ', `motor_serie`=' . (($data['motor_serie'] !== '' && $data['motor_serie'] !== NULL) ? "'{$data['motor_serie']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"equipos_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: equipos_after_insert
	if(function_exists('equipos_after_insert')){
		$res = sql("select * from `equipos` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!equipos_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('equipos', $recID, getLoggedMemberID());

	return $recID;
}

function equipos_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('equipos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='equipos' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='equipos' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: equipos_before_delete
	if(function_exists('equipos_before_delete')){
		$args=array();
		if(!equipos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: equipo_repuestos
	$res = sql("select `id` from `equipos` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `equipo_repuestos` where `interno`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "equipo_repuestos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "equipo_repuestos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='equipos_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='equipos_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: planificacion_equipos
	$res = sql("select `id` from `equipos` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `planificacion_equipos` where `equipo`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_equipos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_equipos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='equipos_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='equipos_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `equipos` where `id`='$selected_id'", $eo);

	// hook: equipos_after_delete
	if(function_exists('equipos_after_delete')){
		$args=array();
		equipos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='equipos' and pkValue='$selected_id'", $eo);
}

function equipos_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('equipos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='equipos' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='equipos' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['interno'] = makeSafe($_REQUEST['interno']);
		if($data['interno'] == empty_lookup_value){ $data['interno'] = ''; }
	$data['articulo'] = makeSafe($_REQUEST['articulo']);
		if($data['articulo'] == empty_lookup_value){ $data['articulo'] = ''; }
	$data['producto'] = br2nl(makeSafe($_REQUEST['producto']));
	$data['marca'] = makeSafe($_REQUEST['marca']);
		if($data['marca'] == empty_lookup_value){ $data['marca'] = ''; }
	$data['modelo'] = makeSafe($_REQUEST['modelo']);
		if($data['modelo'] == empty_lookup_value){ $data['modelo'] = ''; }
	$data['familia'] = makeSafe($_REQUEST['familia']);
		if($data['familia'] == empty_lookup_value){ $data['familia'] = ''; }
	$data['numero_serie'] = makeSafe($_REQUEST['numero_serie']);
		if($data['numero_serie'] == empty_lookup_value){ $data['numero_serie'] = ''; }
	$data['motor_marca'] = makeSafe($_REQUEST['motor_marca']);
		if($data['motor_marca'] == empty_lookup_value){ $data['motor_marca'] = ''; }
	$data['motor_modelo'] = makeSafe($_REQUEST['motor_modelo']);
		if($data['motor_modelo'] == empty_lookup_value){ $data['motor_modelo'] = ''; }
	$data['motor_serie'] = makeSafe($_REQUEST['motor_serie']);
		if($data['motor_serie'] == empty_lookup_value){ $data['motor_serie'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: equipos_before_update
	if(function_exists('equipos_before_update')){
		$args=array();
		if(!equipos_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `equipos` set       `interno`=' . (($data['interno'] !== '' && $data['interno'] !== NULL) ? "'{$data['interno']}'" : 'NULL') . ', `articulo`=' . (($data['articulo'] !== '' && $data['articulo'] !== NULL) ? "'{$data['articulo']}'" : 'NULL') . ', `producto`=' . (($data['producto'] !== '' && $data['producto'] !== NULL) ? "'{$data['producto']}'" : 'NULL') . ', `marca`=' . (($data['marca'] !== '' && $data['marca'] !== NULL) ? "'{$data['marca']}'" : 'NULL') . ', `modelo`=' . (($data['modelo'] !== '' && $data['modelo'] !== NULL) ? "'{$data['modelo']}'" : 'NULL') . ', `familia`=' . (($data['familia'] !== '' && $data['familia'] !== NULL) ? "'{$data['familia']}'" : 'NULL') . ', `numero_serie`=' . (($data['numero_serie'] !== '' && $data['numero_serie'] !== NULL) ? "'{$data['numero_serie']}'" : 'NULL') . ', `motor_marca`=' . (($data['motor_marca'] !== '' && $data['motor_marca'] !== NULL) ? "'{$data['motor_marca']}'" : 'NULL') . ', `motor_modelo`=' . (($data['motor_modelo'] !== '' && $data['motor_modelo'] !== NULL) ? "'{$data['motor_modelo']}'" : 'NULL') . ', `motor_serie`=' . (($data['motor_serie'] !== '' && $data['motor_serie'] !== NULL) ? "'{$data['motor_serie']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="equipos_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: equipos_after_update
	if(function_exists('equipos_after_update')){
		$res = sql("SELECT * FROM `equipos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!equipos_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='equipos' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function equipos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('equipos');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_articulo = thisOr(undo_magic_quotes($_REQUEST['filterer_articulo']), '');
	$filterer_marca = thisOr(undo_magic_quotes($_REQUEST['filterer_marca']), '');
	$filterer_modelo = thisOr(undo_magic_quotes($_REQUEST['filterer_modelo']), '');
	$filterer_familia = thisOr(undo_magic_quotes($_REQUEST['filterer_familia']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_modelo && !$filterer_marca) $filterer_marca = sqlValue("select marca from modelos where id='" . makeSafe($filterer_modelo) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: articulo
	$combo_articulo = new DataCombo;
	// combobox: marca
	$combo_marca = new DataCombo;
	// combobox: modelo, filterable by: marca
	$combo_modelo = new DataCombo;
	// combobox: familia
	$combo_familia = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='equipos' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='equipos' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `equipos` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'equipos_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_articulo->SelectedData = $row['articulo'];
		$combo_marca->SelectedData = $row['marca'];
		$combo_modelo->SelectedData = $row['modelo'];
		$combo_familia->SelectedData = $row['familia'];
	}else{
		$combo_articulo->SelectedData = $filterer_articulo;
		$combo_marca->SelectedData = $filterer_marca;
		$combo_modelo->SelectedData = $filterer_modelo;
		$combo_familia->SelectedData = $filterer_familia;
	}
	$combo_articulo->HTML = '<span id="articulo-container' . $rnd1 . '"></span><input type="hidden" name="articulo" id="articulo' . $rnd1 . '" value="' . html_attr($combo_articulo->SelectedData) . '">';
	$combo_articulo->MatchText = '<span id="articulo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="articulo" id="articulo' . $rnd1 . '" value="' . html_attr($combo_articulo->SelectedData) . '">';
	$combo_marca->HTML = '<span id="marca-container' . $rnd1 . '"></span><input type="hidden" name="marca" id="marca' . $rnd1 . '" value="' . html_attr($combo_marca->SelectedData) . '">';
	$combo_marca->MatchText = '<span id="marca-container-readonly' . $rnd1 . '"></span><input type="hidden" name="marca" id="marca' . $rnd1 . '" value="' . html_attr($combo_marca->SelectedData) . '">';
	$combo_modelo->HTML = '<span id="modelo-container' . $rnd1 . '"></span><input type="hidden" name="modelo" id="modelo' . $rnd1 . '" value="' . html_attr($combo_modelo->SelectedData) . '">';
	$combo_modelo->MatchText = '<span id="modelo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="modelo" id="modelo' . $rnd1 . '" value="' . html_attr($combo_modelo->SelectedData) . '">';
	$combo_familia->HTML = '<span id="familia-container' . $rnd1 . '"></span><input type="hidden" name="familia" id="familia' . $rnd1 . '" value="' . html_attr($combo_familia->SelectedData) . '">';
	$combo_familia->MatchText = '<span id="familia-container-readonly' . $rnd1 . '"></span><input type="hidden" name="familia" id="familia' . $rnd1 . '" value="' . html_attr($combo_familia->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_articulo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['articulo'] : $filterer_articulo); ?>"};
		AppGini.current_marca__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['marca'] : $filterer_marca); ?>"};
		AppGini.current_modelo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['modelo'] : $filterer_modelo); ?>"};
		AppGini.current_familia__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['familia'] : $filterer_familia); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(articulo_reload__RAND__) == 'function') articulo_reload__RAND__();
				if(typeof(marca_reload__RAND__) == 'function') marca_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(modelo_reload__RAND__) == \'function\') modelo_reload__RAND__(AppGini.current_marca__RAND__.value);' : ''); ?>
				if(typeof(familia_reload__RAND__) == 'function') familia_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function articulo_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#articulo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_articulo__RAND__.value, t: 'equipos', f: 'articulo' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="articulo"]').val(resp.results[0].id);
							$j('[id=articulo-container-readonly__RAND__]').html('<span id="articulo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=articulos_view_parent]').hide(); }else{ $j('.btn[id=articulos_view_parent]').show(); }


							if(typeof(articulo_update_autofills__RAND__) == 'function') articulo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'equipos', f: 'articulo' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_articulo__RAND__.value = e.added.id;
				AppGini.current_articulo__RAND__.text = e.added.text;
				$j('[name="articulo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=articulos_view_parent]').hide(); }else{ $j('.btn[id=articulos_view_parent]').show(); }


				if(typeof(articulo_update_autofills__RAND__) == 'function') articulo_update_autofills__RAND__();
			});

			if(!$j("#articulo-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_articulo__RAND__.value, t: 'equipos', f: 'articulo' },
					success: function(resp){
						$j('[name="articulo"]').val(resp.results[0].id);
						$j('[id=articulo-container-readonly__RAND__]').html('<span id="articulo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=articulos_view_parent]').hide(); }else{ $j('.btn[id=articulos_view_parent]').show(); }

						if(typeof(articulo_update_autofills__RAND__) == 'function') articulo_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_articulo__RAND__.value, t: 'equipos', f: 'articulo' },
				success: function(resp){
					$j('[id=articulo-container__RAND__], [id=articulo-container-readonly__RAND__]').html('<span id="articulo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=articulos_view_parent]').hide(); }else{ $j('.btn[id=articulos_view_parent]').show(); }

					if(typeof(articulo_update_autofills__RAND__) == 'function') articulo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function marca_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#marca-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_marca__RAND__.value, t: 'equipos', f: 'marca' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="marca"]').val(resp.results[0].id);
							$j('[id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=marcas_view_parent]').hide(); }else{ $j('.btn[id=marcas_view_parent]').show(); }

						if(typeof(modelo_reload__RAND__) == 'function') modelo_reload__RAND__(AppGini.current_marca__RAND__.value);

							if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'equipos', f: 'marca' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_marca__RAND__.value = e.added.id;
				AppGini.current_marca__RAND__.text = e.added.text;
				$j('[name="marca"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=marcas_view_parent]').hide(); }else{ $j('.btn[id=marcas_view_parent]').show(); }

						if(typeof(modelo_reload__RAND__) == 'function') modelo_reload__RAND__(AppGini.current_marca__RAND__.value);

				if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
			});

			if(!$j("#marca-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_marca__RAND__.value, t: 'equipos', f: 'marca' },
					success: function(resp){
						$j('[name="marca"]').val(resp.results[0].id);
						$j('[id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=marcas_view_parent]').hide(); }else{ $j('.btn[id=marcas_view_parent]').show(); }

						if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_marca__RAND__.value, t: 'equipos', f: 'marca' },
				success: function(resp){
					$j('[id=marca-container__RAND__], [id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=marcas_view_parent]').hide(); }else{ $j('.btn[id=marcas_view_parent]').show(); }

					if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function modelo_reload__RAND__(filterer_marca){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#modelo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_marca: filterer_marca, id: AppGini.current_modelo__RAND__.value, t: 'equipos', f: 'modelo' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="modelo"]').val(resp.results[0].id);
							$j('[id=modelo-container-readonly__RAND__]').html('<span id="modelo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=modelos_view_parent]').hide(); }else{ $j('.btn[id=modelos_view_parent]').show(); }


							if(typeof(modelo_update_autofills__RAND__) == 'function') modelo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { filterer_marca: filterer_marca, s: term, p: page, t: 'equipos', f: 'modelo' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_modelo__RAND__.value = e.added.id;
				AppGini.current_modelo__RAND__.text = e.added.text;
				$j('[name="modelo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=modelos_view_parent]').hide(); }else{ $j('.btn[id=modelos_view_parent]').show(); }


				if(typeof(modelo_update_autofills__RAND__) == 'function') modelo_update_autofills__RAND__();
			});

			if(!$j("#modelo-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_modelo__RAND__.value, t: 'equipos', f: 'modelo' },
					success: function(resp){
						$j('[name="modelo"]').val(resp.results[0].id);
						$j('[id=modelo-container-readonly__RAND__]').html('<span id="modelo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=modelos_view_parent]').hide(); }else{ $j('.btn[id=modelos_view_parent]').show(); }

						if(typeof(modelo_update_autofills__RAND__) == 'function') modelo_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_modelo__RAND__.value, t: 'equipos', f: 'modelo' },
				success: function(resp){
					$j('[id=modelo-container__RAND__], [id=modelo-container-readonly__RAND__]').html('<span id="modelo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=modelos_view_parent]').hide(); }else{ $j('.btn[id=modelos_view_parent]').show(); }

					if(typeof(modelo_update_autofills__RAND__) == 'function') modelo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function familia_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#familia-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_familia__RAND__.value, t: 'equipos', f: 'familia' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="familia"]').val(resp.results[0].id);
							$j('[id=familia-container-readonly__RAND__]').html('<span id="familia-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=familias_view_parent]').hide(); }else{ $j('.btn[id=familias_view_parent]').show(); }


							if(typeof(familia_update_autofills__RAND__) == 'function') familia_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'equipos', f: 'familia' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_familia__RAND__.value = e.added.id;
				AppGini.current_familia__RAND__.text = e.added.text;
				$j('[name="familia"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=familias_view_parent]').hide(); }else{ $j('.btn[id=familias_view_parent]').show(); }


				if(typeof(familia_update_autofills__RAND__) == 'function') familia_update_autofills__RAND__();
			});

			if(!$j("#familia-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_familia__RAND__.value, t: 'equipos', f: 'familia' },
					success: function(resp){
						$j('[name="familia"]').val(resp.results[0].id);
						$j('[id=familia-container-readonly__RAND__]').html('<span id="familia-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=familias_view_parent]').hide(); }else{ $j('.btn[id=familias_view_parent]').show(); }

						if(typeof(familia_update_autofills__RAND__) == 'function') familia_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_familia__RAND__.value, t: 'equipos', f: 'familia' },
				success: function(resp){
					$j('[id=familia-container__RAND__], [id=familia-container-readonly__RAND__]').html('<span id="familia-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=familias_view_parent]').hide(); }else{ $j('.btn[id=familias_view_parent]').show(); }

					if(typeof(familia_update_autofills__RAND__) == 'function') familia_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/equipos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/equipos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Equipo details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return equipos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return equipos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return equipos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#interno').replaceWith('<div class=\"form-control-static\" id=\"interno\">' + (jQuery('#interno').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#articulo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#articulo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#producto').replaceWith('<div class=\"form-control-static\" id=\"producto\">' + (jQuery('#producto').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#marca').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#marca_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#modelo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#modelo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#familia').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#familia_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#numero_serie').replaceWith('<div class=\"form-control-static\" id=\"numero_serie\">' + (jQuery('#numero_serie').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#motor_marca').replaceWith('<div class=\"form-control-static\" id=\"motor_marca\">' + (jQuery('#motor_marca').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#motor_modelo').replaceWith('<div class=\"form-control-static\" id=\"motor_modelo\">' + (jQuery('#motor_modelo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#motor_serie').replaceWith('<div class=\"form-control-static\" id=\"motor_serie\">' + (jQuery('#motor_serie').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(articulo)%%>', $combo_articulo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(articulo)%%>', $combo_articulo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(articulo)%%>', urlencode($combo_articulo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(marca)%%>', $combo_marca->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(marca)%%>', $combo_marca->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(marca)%%>', urlencode($combo_marca->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(modelo)%%>', $combo_modelo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(modelo)%%>', $combo_modelo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(modelo)%%>', urlencode($combo_modelo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(familia)%%>', $combo_familia->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(familia)%%>', $combo_familia->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(familia)%%>', urlencode($combo_familia->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'articulo' => array('articulos', 'Articulo'), 'marca' => array('marcas', 'Marca'), 'modelo' => array('modelos', 'Modelo'), 'familia' => array('familias', 'Familia'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(interno)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(articulo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(producto)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(marca)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(modelo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(familia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(numero_serie)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motor_marca)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motor_modelo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(motor_serie)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(interno)%%>', safe_html($urow['interno']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(interno)%%>', html_attr($row['interno']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(interno)%%>', urlencode($urow['interno']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(articulo)%%>', safe_html($urow['articulo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(articulo)%%>', html_attr($row['articulo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(articulo)%%>', urlencode($urow['articulo']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)){
			$templateCode = str_replace('<%%VALUE(producto)%%>', safe_html($urow['producto']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(producto)%%>', html_attr($row['producto']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(producto)%%>', urlencode($urow['producto']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(marca)%%>', safe_html($urow['marca']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(marca)%%>', html_attr($row['marca']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marca)%%>', urlencode($urow['marca']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(modelo)%%>', safe_html($urow['modelo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(modelo)%%>', html_attr($row['modelo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(modelo)%%>', urlencode($urow['modelo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(familia)%%>', safe_html($urow['familia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(familia)%%>', html_attr($row['familia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(familia)%%>', urlencode($urow['familia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(numero_serie)%%>', safe_html($urow['numero_serie']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(numero_serie)%%>', html_attr($row['numero_serie']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero_serie)%%>', urlencode($urow['numero_serie']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motor_marca)%%>', safe_html($urow['motor_marca']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motor_marca)%%>', html_attr($row['motor_marca']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_marca)%%>', urlencode($urow['motor_marca']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motor_modelo)%%>', safe_html($urow['motor_modelo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motor_modelo)%%>', html_attr($row['motor_modelo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_modelo)%%>', urlencode($urow['motor_modelo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(motor_serie)%%>', safe_html($urow['motor_serie']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(motor_serie)%%>', html_attr($row['motor_serie']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_serie)%%>', urlencode($urow['motor_serie']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(interno)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(interno)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(articulo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(articulo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(producto)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(producto)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(marca)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marca)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(modelo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(modelo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(familia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(familia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(numero_serie)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero_serie)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motor_marca)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_marca)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motor_modelo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_modelo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(motor_serie)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(motor_serie)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('equipos');
	if($selected_id){
		$jdata = get_joined_record('equipos', $selected_id);
		if($jdata === false) $jdata = get_defaults('equipos');
		$rdata = $row;
	}
	$templateCode .= loadView('equipos-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: equipos_dv
	if(function_exists('equipos_dv')){
		$args=array();
		equipos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>