<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/equipos.php");
	include("$currDir/equipos_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('equipos');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "equipos";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`equipos`.`id`" => "id",
		"`equipos`.`interno`" => "interno",
		"IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') /* Articulo */" => "articulo",
		"IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') /* Marca */" => "marca",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') /* Familia */" => "familia"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`equipos`.`id`',
		2 => 2,
		3 => '`articulos1`.`articulo`',
		4 => '`marcas1`.`marca`',
		5 => '`modelos1`.`modelo`',
		6 => '`familias1`.`familia`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`equipos`.`id`" => "id",
		"`equipos`.`interno`" => "interno",
		"IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') /* Articulo */" => "articulo",
		"IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') /* Marca */" => "marca",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') /* Familia */" => "familia"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`equipos`.`id`" => "ID",
		"`equipos`.`interno`" => "Interno",
		"IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') /* Articulo */" => "Articulo",
		"IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') /* Marca */" => "Marca",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "Modelo",
		"IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') /* Familia */" => "Familia"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`equipos`.`id`" => "id",
		"`equipos`.`interno`" => "interno",
		"IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') /* Articulo */" => "articulo",
		"IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') /* Marca */" => "marca",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') /* Familia */" => "familia"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'articulo' => 'Articulo', 'marca' => 'Marca', 'modelo' => 'Modelo', 'familia' => 'Familia');

	$x->QueryFrom = "`equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "equipos_view.php";
	$x->RedirectAfterInsert = "equipos_view.php?SelectedID=#ID#";
	$x->TableTitle = "Equipos";
	$x->TableIcon = "resources/table_icons/autos.png";
	$x->PrimaryKey = "`equipos`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Interno", "Articulo", "Marca", "Modelo", "Familia");
	$x->ColFieldName = array('interno', 'articulo', 'marca', 'modelo', 'familia');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/equipos_templateTV.html';
	$x->SelectedTemplate = 'templates/equipos_templateTVS.html';
	$x->TemplateDV = 'templates/equipos_templateDV.html';
	$x->TemplateDVP = 'templates/equipos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `equipos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='equipos' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `equipos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='equipos' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`equipos`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: equipos_init
	$render=TRUE;
	if(function_exists('equipos_init')){
		$args=array();
		$render=equipos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: equipos_header
	$headerCode='';
	if(function_exists('equipos_header')){
		$args=array();
		$headerCode=equipos_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: equipos_footer
	$footerCode='';
	if(function_exists('equipos_footer')){
		$args=array();
		$footerCode=equipos_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>