<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'equipos' => array(   
				'articulo' => array(   
					'parent-table' => 'articulos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipos <span class="hidden child-label-equipos child-field-caption">(Articulo)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Articulo', 3 => 'Marca', 4 => 'Modelo', 5 => 'Familia'),
					'display-field-names' => array(1 => 'interno', 2 => 'articulo', 3 => 'marca', 4 => 'modelo', 5 => 'familia'),
					'sortable-fields' => array(0 => '`equipos`.`id`', 1 => 2, 2 => '`articulos1`.`articulo`', 3 => '`marcas1`.`marca`', 4 => '`modelos1`.`modelo`', 5 => '`familias1`.`familia`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipos',
					'template-printable' => 'children-equipos-printable',
					'query' => "SELECT `equipos`.`id` as 'id', `equipos`.`interno` as 'interno', IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') as 'articulo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') as 'familia' FROM `equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia` "
				),
				'marca' => array(   
					'parent-table' => 'marcas',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipos <span class="hidden child-label-equipos child-field-caption">(Marca)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Articulo', 3 => 'Marca', 4 => 'Modelo', 5 => 'Familia'),
					'display-field-names' => array(1 => 'interno', 2 => 'articulo', 3 => 'marca', 4 => 'modelo', 5 => 'familia'),
					'sortable-fields' => array(0 => '`equipos`.`id`', 1 => 2, 2 => '`articulos1`.`articulo`', 3 => '`marcas1`.`marca`', 4 => '`modelos1`.`modelo`', 5 => '`familias1`.`familia`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipos',
					'template-printable' => 'children-equipos-printable',
					'query' => "SELECT `equipos`.`id` as 'id', `equipos`.`interno` as 'interno', IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') as 'articulo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') as 'familia' FROM `equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia` "
				),
				'modelo' => array(   
					'parent-table' => 'modelos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipos <span class="hidden child-label-equipos child-field-caption">(Modelo)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Articulo', 3 => 'Marca', 4 => 'Modelo', 5 => 'Familia'),
					'display-field-names' => array(1 => 'interno', 2 => 'articulo', 3 => 'marca', 4 => 'modelo', 5 => 'familia'),
					'sortable-fields' => array(0 => '`equipos`.`id`', 1 => 2, 2 => '`articulos1`.`articulo`', 3 => '`marcas1`.`marca`', 4 => '`modelos1`.`modelo`', 5 => '`familias1`.`familia`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipos',
					'template-printable' => 'children-equipos-printable',
					'query' => "SELECT `equipos`.`id` as 'id', `equipos`.`interno` as 'interno', IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') as 'articulo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') as 'familia' FROM `equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia` "
				),
				'familia' => array(   
					'parent-table' => 'familias',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipos <span class="hidden child-label-equipos child-field-caption">(Familia)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Articulo', 3 => 'Marca', 4 => 'Modelo', 5 => 'Familia'),
					'display-field-names' => array(1 => 'interno', 2 => 'articulo', 3 => 'marca', 4 => 'modelo', 5 => 'familia'),
					'sortable-fields' => array(0 => '`equipos`.`id`', 1 => 2, 2 => '`articulos1`.`articulo`', 3 => '`marcas1`.`marca`', 4 => '`modelos1`.`modelo`', 5 => '`familias1`.`familia`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipos',
					'template-printable' => 'children-equipos-printable',
					'query' => "SELECT `equipos`.`id` as 'id', `equipos`.`interno` as 'interno', IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') as 'articulo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') as 'familia' FROM `equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia` "
				)
			),
			'modelos' => array(   
				'marca' => array(   
					'parent-table' => 'marcas',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Modelos <span class="hidden child-label-modelos child-field-caption">(Marca)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Modelo', 2 => 'Marca'),
					'display-field-names' => array(1 => 'modelo', 2 => 'marca'),
					'sortable-fields' => array(0 => '`modelos`.`id`', 1 => 2, 2 => '`marcas1`.`marca`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-modelos',
					'template-printable' => 'children-modelos-printable',
					'query' => "SELECT `modelos`.`id` as 'id', `modelos`.`modelo` as 'modelo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca' FROM `modelos` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`modelos`.`marca` "
				)
			),
			'familias' => array(   
			),
			'repuestos' => array(   
			),
			'articulos' => array(   
			),
			'marcas' => array(   
			),
			'equipo_repuestos' => array(   
				'interno' => array(   
					'parent-table' => 'equipos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipo repuestos <span class="hidden child-label-equipo_repuestos child-field-caption">(Interno)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Repuesto', 3 => 'Descripcion', 4 => 'Cantidad'),
					'display-field-names' => array(1 => 'interno', 2 => 'codigo', 3 => 'descripcion', 4 => 'cantidad'),
					'sortable-fields' => array(0 => '`equipo_repuestos`.`id`', 1 => '`equipos1`.`interno`', 2 => '`repuestos1`.`codigo`', 3 => '`repuestos1`.`descripcion`', 4 => 5),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipo_repuestos',
					'template-printable' => 'children-equipo_repuestos-printable',
					'query' => "SELECT `equipo_repuestos`.`id` as 'id', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'interno', IF(    CHAR_LENGTH(`repuestos1`.`codigo`), CONCAT_WS('',   `repuestos1`.`codigo`), '') as 'codigo', IF(    CHAR_LENGTH(`repuestos1`.`descripcion`), CONCAT_WS('',   `repuestos1`.`descripcion`), '') as 'descripcion', `equipo_repuestos`.`cantidad` as 'cantidad' FROM `equipo_repuestos` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`equipo_repuestos`.`interno` LEFT JOIN `repuestos` as repuestos1 ON `repuestos1`.`id`=`equipo_repuestos`.`codigo` "
				),
				'codigo' => array(   
					'parent-table' => 'repuestos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Equipo repuestos <span class="hidden child-label-equipo_repuestos child-field-caption">(Repuesto)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Interno', 2 => 'Repuesto', 3 => 'Descripcion', 4 => 'Cantidad'),
					'display-field-names' => array(1 => 'interno', 2 => 'codigo', 3 => 'descripcion', 4 => 'cantidad'),
					'sortable-fields' => array(0 => '`equipo_repuestos`.`id`', 1 => '`equipos1`.`interno`', 2 => '`repuestos1`.`codigo`', 3 => '`repuestos1`.`descripcion`', 4 => 5),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-equipo_repuestos',
					'template-printable' => 'children-equipo_repuestos-printable',
					'query' => "SELECT `equipo_repuestos`.`id` as 'id', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'interno', IF(    CHAR_LENGTH(`repuestos1`.`codigo`), CONCAT_WS('',   `repuestos1`.`codigo`), '') as 'codigo', IF(    CHAR_LENGTH(`repuestos1`.`descripcion`), CONCAT_WS('',   `repuestos1`.`descripcion`), '') as 'descripcion', `equipo_repuestos`.`cantidad` as 'cantidad' FROM `equipo_repuestos` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`equipo_repuestos`.`interno` LEFT JOIN `repuestos` as repuestos1 ON `repuestos1`.`id`=`equipo_repuestos`.`codigo` "
				)
			),
			'tecnicos' => array(   
			),
			'planificaciones' => array(   
				'tecnico' => array(   
					'parent-table' => 'tecnicos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificaciones <span class="hidden child-label-planificaciones child-field-caption">(Tecnico)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Titulo', 2 => 'Tecnico', 3 => 'Camioneta', 4 => 'Fecha planificado'),
					'display-field-names' => array(1 => 'titulo', 2 => 'tecnico', 3 => 'camioneta', 4 => 'fecha_planificado'),
					'sortable-fields' => array(0 => '`planificaciones`.`id`', 1 => 2, 2 => '`tecnicos1`.`nombre`', 3 => 4, 4 => '`planificaciones`.`fecha_planificado`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificaciones',
					'template-printable' => 'children-planificaciones-printable',
					'query' => "SELECT `planificaciones`.`id` as 'id', `planificaciones`.`titulo` as 'titulo', IF(    CHAR_LENGTH(`tecnicos1`.`nombre`), CONCAT_WS('',   `tecnicos1`.`nombre`), '') as 'tecnico', IF(    CHAR_LENGTH(`camionetas1`.`interno`) || CHAR_LENGTH(`camionetas1`.`matricula`), CONCAT_WS('',   `camionetas1`.`interno`, ' - ', `camionetas1`.`matricula`), '') as 'camioneta', if(`planificaciones`.`fecha_planificado`,date_format(`planificaciones`.`fecha_planificado`,'%m/%d/%Y'),'') as 'fecha_planificado' FROM `planificaciones` LEFT JOIN `tecnicos` as tecnicos1 ON `tecnicos1`.`id`=`planificaciones`.`tecnico` LEFT JOIN `camionetas` as camionetas1 ON `camionetas1`.`id`=`planificaciones`.`camioneta` "
				),
				'camioneta' => array(   
					'parent-table' => 'camionetas',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificaciones <span class="hidden child-label-planificaciones child-field-caption">(Camioneta)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Titulo', 2 => 'Tecnico', 3 => 'Camioneta', 4 => 'Fecha planificado'),
					'display-field-names' => array(1 => 'titulo', 2 => 'tecnico', 3 => 'camioneta', 4 => 'fecha_planificado'),
					'sortable-fields' => array(0 => '`planificaciones`.`id`', 1 => 2, 2 => '`tecnicos1`.`nombre`', 3 => 4, 4 => '`planificaciones`.`fecha_planificado`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificaciones',
					'template-printable' => 'children-planificaciones-printable',
					'query' => "SELECT `planificaciones`.`id` as 'id', `planificaciones`.`titulo` as 'titulo', IF(    CHAR_LENGTH(`tecnicos1`.`nombre`), CONCAT_WS('',   `tecnicos1`.`nombre`), '') as 'tecnico', IF(    CHAR_LENGTH(`camionetas1`.`interno`) || CHAR_LENGTH(`camionetas1`.`matricula`), CONCAT_WS('',   `camionetas1`.`interno`, ' - ', `camionetas1`.`matricula`), '') as 'camioneta', if(`planificaciones`.`fecha_planificado`,date_format(`planificaciones`.`fecha_planificado`,'%m/%d/%Y'),'') as 'fecha_planificado' FROM `planificaciones` LEFT JOIN `tecnicos` as tecnicos1 ON `tecnicos1`.`id`=`planificaciones`.`tecnico` LEFT JOIN `camionetas` as camionetas1 ON `camionetas1`.`id`=`planificaciones`.`camioneta` "
				)
			),
			'planificacion_equipos' => array(   
				'planificacion' => array(   
					'parent-table' => 'planificaciones',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificacion equipos <span class="hidden child-label-planificacion_equipos child-field-caption">(Planificacion)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Planificacion', 2 => 'Cliente', 3 => 'Equipo', 4 => 'Modelo', 5 => 'Ubicacion', 6 => 'Horometro', 7 => 'Cumplido', 8 => 'Comentarios', 9 => 'Fecha cumplido', 10 => 'Distancia'),
					'display-field-names' => array(1 => 'planificacion', 2 => 'cliente', 3 => 'equipo', 4 => 'modelo', 5 => 'ubicacion', 6 => 'horometro', 7 => 'cumplido', 8 => 'comentarios', 9 => 'fecha_cumplido', 10 => 'distancia'),
					'sortable-fields' => array(0 => '`planificacion_equipos`.`id`', 1 => '`planificaciones1`.`titulo`', 2 => '`clientes1`.`nombre`', 3 => '`equipos1`.`interno`', 4 => 5, 5 => 6, 6 => 7, 7 => '`planificacion_equipos`.`cumplido`', 8 => 9, 9 => '`planificacion_equipos`.`fecha_cumplido`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificacion_equipos',
					'template-printable' => 'children-planificacion_equipos-printable',
					'query' => "SELECT `planificacion_equipos`.`id` as 'id', IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') as 'planificacion', IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') as 'cliente', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'equipo', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', `planificacion_equipos`.`ubicacion` as 'ubicacion', `planificacion_equipos`.`horometro` as 'horometro', concat('<i class=\"glyphicon glyphicon-', if(`planificacion_equipos`.`cumplido`, 'check', 'unchecked'), '\"></i>') as 'cumplido', `planificacion_equipos`.`comentarios` as 'comentarios', if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'') as 'fecha_cumplido', `planificacion_equipos`.`distancia` as 'distancia' FROM `planificacion_equipos` LEFT JOIN `planificaciones` as planificaciones1 ON `planificaciones1`.`id`=`planificacion_equipos`.`planificacion` LEFT JOIN `clientes` as clientes1 ON `clientes1`.`id`=`planificacion_equipos`.`cliente` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`planificacion_equipos`.`equipo` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos1`.`modelo` "
				),
				'cliente' => array(   
					'parent-table' => 'clientes',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificacion equipos <span class="hidden child-label-planificacion_equipos child-field-caption">(Cliente)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Planificacion', 2 => 'Cliente', 3 => 'Equipo', 4 => 'Modelo', 5 => 'Ubicacion', 6 => 'Horometro', 7 => 'Cumplido', 8 => 'Comentarios', 9 => 'Fecha cumplido', 10 => 'Distancia'),
					'display-field-names' => array(1 => 'planificacion', 2 => 'cliente', 3 => 'equipo', 4 => 'modelo', 5 => 'ubicacion', 6 => 'horometro', 7 => 'cumplido', 8 => 'comentarios', 9 => 'fecha_cumplido', 10 => 'distancia'),
					'sortable-fields' => array(0 => '`planificacion_equipos`.`id`', 1 => '`planificaciones1`.`titulo`', 2 => '`clientes1`.`nombre`', 3 => '`equipos1`.`interno`', 4 => 5, 5 => 6, 6 => 7, 7 => '`planificacion_equipos`.`cumplido`', 8 => 9, 9 => '`planificacion_equipos`.`fecha_cumplido`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificacion_equipos',
					'template-printable' => 'children-planificacion_equipos-printable',
					'query' => "SELECT `planificacion_equipos`.`id` as 'id', IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') as 'planificacion', IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') as 'cliente', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'equipo', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', `planificacion_equipos`.`ubicacion` as 'ubicacion', `planificacion_equipos`.`horometro` as 'horometro', concat('<i class=\"glyphicon glyphicon-', if(`planificacion_equipos`.`cumplido`, 'check', 'unchecked'), '\"></i>') as 'cumplido', `planificacion_equipos`.`comentarios` as 'comentarios', if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'') as 'fecha_cumplido', `planificacion_equipos`.`distancia` as 'distancia' FROM `planificacion_equipos` LEFT JOIN `planificaciones` as planificaciones1 ON `planificaciones1`.`id`=`planificacion_equipos`.`planificacion` LEFT JOIN `clientes` as clientes1 ON `clientes1`.`id`=`planificacion_equipos`.`cliente` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`planificacion_equipos`.`equipo` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos1`.`modelo` "
				),
				'equipo' => array(   
					'parent-table' => 'equipos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificacion equipos <span class="hidden child-label-planificacion_equipos child-field-caption">(Equipo)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Planificacion', 2 => 'Cliente', 3 => 'Equipo', 4 => 'Modelo', 5 => 'Ubicacion', 6 => 'Horometro', 7 => 'Cumplido', 8 => 'Comentarios', 9 => 'Fecha cumplido', 10 => 'Distancia'),
					'display-field-names' => array(1 => 'planificacion', 2 => 'cliente', 3 => 'equipo', 4 => 'modelo', 5 => 'ubicacion', 6 => 'horometro', 7 => 'cumplido', 8 => 'comentarios', 9 => 'fecha_cumplido', 10 => 'distancia'),
					'sortable-fields' => array(0 => '`planificacion_equipos`.`id`', 1 => '`planificaciones1`.`titulo`', 2 => '`clientes1`.`nombre`', 3 => '`equipos1`.`interno`', 4 => 5, 5 => 6, 6 => 7, 7 => '`planificacion_equipos`.`cumplido`', 8 => 9, 9 => '`planificacion_equipos`.`fecha_cumplido`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificacion_equipos',
					'template-printable' => 'children-planificacion_equipos-printable',
					'query' => "SELECT `planificacion_equipos`.`id` as 'id', IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') as 'planificacion', IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') as 'cliente', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'equipo', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', `planificacion_equipos`.`ubicacion` as 'ubicacion', `planificacion_equipos`.`horometro` as 'horometro', concat('<i class=\"glyphicon glyphicon-', if(`planificacion_equipos`.`cumplido`, 'check', 'unchecked'), '\"></i>') as 'cumplido', `planificacion_equipos`.`comentarios` as 'comentarios', if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'') as 'fecha_cumplido', `planificacion_equipos`.`distancia` as 'distancia' FROM `planificacion_equipos` LEFT JOIN `planificaciones` as planificaciones1 ON `planificaciones1`.`id`=`planificacion_equipos`.`planificacion` LEFT JOIN `clientes` as clientes1 ON `clientes1`.`id`=`planificacion_equipos`.`cliente` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`planificacion_equipos`.`equipo` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos1`.`modelo` "
				)
			),
			'codigo_servicios' => array(   
			),
			'camionetas' => array(   
			),
			'clientes' => array(   
			),
			'planificacion_pendientes' => array(   
				'planificacion' => array(   
					'parent-table' => 'planificacion_equipos',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Planificacion pendientes <span class="hidden child-label-planificacion_pendientes child-field-caption">(Planificacion)</span>',
					'auto-close' => false,
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Planificacion', 2 => 'Interno', 3 => 'Comentario'),
					'display-field-names' => array(1 => 'planificacion', 2 => 'interno', 3 => 'comentario'),
					'sortable-fields' => array(0 => '`planificacion_pendientes`.`id`', 1 => 2, 2 => 3, 3 => 4),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-planificacion_pendientes',
					'template-printable' => 'children-planificacion_pendientes-printable',
					'query' => "SELECT `planificacion_pendientes`.`id` as 'id', IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') as 'planificacion', IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') as 'interno', `planificacion_pendientes`.`comentario` as 'comentario' FROM `planificacion_pendientes` LEFT JOIN `planificacion_equipos` as planificacion_equipos1 ON `planificacion_equipos1`.`id`=`planificacion_pendientes`.`planificacion` LEFT JOIN `planificaciones` as planificaciones1 ON `planificaciones1`.`id`=`planificacion_equipos1`.`planificacion` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`planificacion_equipos1`.`equipo` "
				)
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>

					/* show child field caption on tab title in case the same child table appears more than once */
					$j('.child-field-caption').each(function() {
						var clss = $j(this).attr('class').split(/\s+/).reduce(function(rc, cc) {
							return (cc.match(/child-label-.*/) ? '.' + cc : rc);
						}, '');

						// if class occurs more than once, remove .hidden
						if($j(clss).length > 1) $j(clss).removeClass('hidden');
					})
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
