<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/planificacion_equipos.php");
	include("$currDir/planificacion_equipos_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('planificacion_equipos');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "planificacion_equipos";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`planificacion_equipos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') /* Planificacion */" => "planificacion",
		"IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') /* Cliente */" => "cliente",
		"IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') /* Equipo */" => "equipo",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`codigo_servicios1`.`servicio`), CONCAT_WS('',   `codigo_servicios1`.`servicio`), '') /* Servicio */" => "servicio",
		"`planificacion_equipos`.`ubicacion`" => "ubicacion",
		"`planificacion_equipos`.`horometro`" => "horometro",
		"concat('<i class=\"glyphicon glyphicon-', if(`planificacion_equipos`.`cumplido`, 'check', 'unchecked'), '\"></i>')" => "cumplido",
		"`planificacion_equipos`.`comentarios`" => "comentarios",
		"if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'')" => "fecha_cumplido",
		"`planificacion_equipos`.`distancia`" => "distancia"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`planificacion_equipos`.`id`',
		2 => '`planificaciones1`.`titulo`',
		3 => '`clientes1`.`nombre`',
		4 => '`equipos1`.`interno`',
		5 => 5,
		6 => '`codigo_servicios1`.`servicio`',
		7 => 7,
		8 => 8,
		9 => '`planificacion_equipos`.`cumplido`',
		10 => 10,
		11 => '`planificacion_equipos`.`fecha_cumplido`',
		12 => 12
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`planificacion_equipos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') /* Planificacion */" => "planificacion",
		"IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') /* Cliente */" => "cliente",
		"IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') /* Equipo */" => "equipo",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`codigo_servicios1`.`servicio`), CONCAT_WS('',   `codigo_servicios1`.`servicio`), '') /* Servicio */" => "servicio",
		"`planificacion_equipos`.`ubicacion`" => "ubicacion",
		"`planificacion_equipos`.`horometro`" => "horometro",
		"`planificacion_equipos`.`cumplido`" => "cumplido",
		"`planificacion_equipos`.`comentarios`" => "comentarios",
		"if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'')" => "fecha_cumplido",
		"`planificacion_equipos`.`distancia`" => "distancia"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`planificacion_equipos`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') /* Planificacion */" => "Planificacion",
		"IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') /* Cliente */" => "Cliente",
		"IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') /* Equipo */" => "Equipo",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "Modelo",
		"IF(    CHAR_LENGTH(`codigo_servicios1`.`servicio`), CONCAT_WS('',   `codigo_servicios1`.`servicio`), '') /* Servicio */" => "Servicio",
		"`planificacion_equipos`.`ubicacion`" => "Ubicacion",
		"`planificacion_equipos`.`horometro`" => "Horometro",
		"`planificacion_equipos`.`cumplido`" => "Cumplido",
		"`planificacion_equipos`.`comentarios`" => "Comentarios",
		"`planificacion_equipos`.`fecha_cumplido`" => "Fecha cumplido",
		"`planificacion_equipos`.`distancia`" => "Distancia"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`planificacion_equipos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`planificaciones1`.`titulo`), CONCAT_WS('',   `planificaciones1`.`titulo`), '') /* Planificacion */" => "planificacion",
		"IF(    CHAR_LENGTH(`clientes1`.`nombre`), CONCAT_WS('',   `clientes1`.`nombre`), '') /* Cliente */" => "cliente",
		"IF(    CHAR_LENGTH(`equipos1`.`interno`), CONCAT_WS('',   `equipos1`.`interno`), '') /* Equipo */" => "equipo",
		"IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') /* Modelo */" => "modelo",
		"IF(    CHAR_LENGTH(`codigo_servicios1`.`servicio`), CONCAT_WS('',   `codigo_servicios1`.`servicio`), '') /* Servicio */" => "servicio",
		"`planificacion_equipos`.`ubicacion`" => "ubicacion",
		"`planificacion_equipos`.`horometro`" => "horometro",
		"concat('<i class=\"glyphicon glyphicon-', if(`planificacion_equipos`.`cumplido`, 'check', 'unchecked'), '\"></i>')" => "cumplido",
		"`planificacion_equipos`.`comentarios`" => "comentarios",
		"if(`planificacion_equipos`.`fecha_cumplido`,date_format(`planificacion_equipos`.`fecha_cumplido`,'%m/%d/%Y'),'')" => "fecha_cumplido",
		"`planificacion_equipos`.`distancia`" => "distancia"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'planificacion' => 'Planificacion', 'cliente' => 'Cliente', 'equipo' => 'Equipo', 'servicio' => 'Servicio');

	$x->QueryFrom = "`planificacion_equipos` LEFT JOIN `planificaciones` as planificaciones1 ON `planificaciones1`.`id`=`planificacion_equipos`.`planificacion` LEFT JOIN `clientes` as clientes1 ON `clientes1`.`id`=`planificacion_equipos`.`cliente` LEFT JOIN `equipos` as equipos1 ON `equipos1`.`id`=`planificacion_equipos`.`equipo` LEFT JOIN `codigo_servicios` as codigo_servicios1 ON `codigo_servicios1`.`id`=`planificacion_equipos`.`servicio` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos1`.`modelo` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "planificacion_equipos_view.php";
	$x->RedirectAfterInsert = "planificacion_equipos_view.php?SelectedID=#ID#";
	$x->TableTitle = "Planificacion equipos";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`planificacion_equipos`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Planificacion", "Cliente", "Equipo", "Modelo", "Servicio", "Ubicacion", "Horometro", "Cumplido", "Comentarios", "Fecha cumplido", "Distancia");
	$x->ColFieldName = array('planificacion', 'cliente', 'equipo', 'modelo', 'servicio', 'ubicacion', 'horometro', 'cumplido', 'comentarios', 'fecha_cumplido', 'distancia');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/planificacion_equipos_templateTV.html';
	$x->SelectedTemplate = 'templates/planificacion_equipos_templateTVS.html';
	$x->TemplateDV = 'templates/planificacion_equipos_templateDV.html';
	$x->TemplateDVP = 'templates/planificacion_equipos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `planificacion_equipos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='planificacion_equipos' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `planificacion_equipos`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='planificacion_equipos' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`planificacion_equipos`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: planificacion_equipos_init
	$render=TRUE;
	if(function_exists('planificacion_equipos_init')){
		$args=array();
		$render=planificacion_equipos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: planificacion_equipos_header
	$headerCode='';
	if(function_exists('planificacion_equipos_header')){
		$args=array();
		$headerCode=planificacion_equipos_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: planificacion_equipos_footer
	$footerCode='';
	if(function_exists('planificacion_equipos_footer')){
		$args=array();
		$footerCode=planificacion_equipos_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>