<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('planificacion_equipos');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'equipo':
			if(!$id){
				?>
				$j('#modelo<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `equipos`.`id` as 'id', `equipos`.`interno` as 'interno', IF(    CHAR_LENGTH(`articulos1`.`articulo`), CONCAT_WS('',   `articulos1`.`articulo`), '') as 'articulo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`modelos1`.`modelo`), CONCAT_WS('',   `modelos1`.`modelo`), '') as 'modelo', IF(    CHAR_LENGTH(`familias1`.`familia`), CONCAT_WS('',   `familias1`.`familia`), '') as 'familia', `equipos`.`numero_serie` as 'numero_serie', `equipos`.`motor_marca` as 'motor_marca', `equipos`.`motor_modelo` as 'motor_modelo', `equipos`.`motor_serie` as 'motor_serie' FROM `equipos` LEFT JOIN `articulos` as articulos1 ON `articulos1`.`id`=`equipos`.`articulo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id`=`equipos`.`marca` LEFT JOIN `modelos` as modelos1 ON `modelos1`.`id`=`equipos`.`modelo` LEFT JOIN `familias` as familias1 ON `familias1`.`id`=`equipos`.`familia`  WHERE `equipos`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#modelo<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['modelo']))); ?>&nbsp;');
			<?php
			break;


	}

?>