<?php

// Data functions (insert, update, delete, form) for table planificacion_equipos

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function planificacion_equipos_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('planificacion_equipos');
	if(!$arrPerm[1]){
		return false;
	}

	$data['planificacion'] = makeSafe($_REQUEST['planificacion']);
		if($data['planificacion'] == empty_lookup_value){ $data['planificacion'] = ''; }
	$data['cliente'] = makeSafe($_REQUEST['cliente']);
		if($data['cliente'] == empty_lookup_value){ $data['cliente'] = ''; }
	$data['equipo'] = makeSafe($_REQUEST['equipo']);
		if($data['equipo'] == empty_lookup_value){ $data['equipo'] = ''; }
	$data['modelo'] = makeSafe($_REQUEST['equipo']);
		if($data['modelo'] == empty_lookup_value){ $data['modelo'] = ''; }
	$data['ubicacion'] = makeSafe($_REQUEST['ubicacion']);
		if($data['ubicacion'] == empty_lookup_value){ $data['ubicacion'] = ''; }
	$data['horometro'] = makeSafe($_REQUEST['horometro']);
		if($data['horometro'] == empty_lookup_value){ $data['horometro'] = ''; }
	$data['cumplido'] = makeSafe($_REQUEST['cumplido']);
		if($data['cumplido'] == empty_lookup_value){ $data['cumplido'] = ''; }
	$data['comentarios'] = makeSafe($_REQUEST['comentarios']);
		if($data['comentarios'] == empty_lookup_value){ $data['comentarios'] = ''; }
	$data['fecha_cumplido'] = intval($_REQUEST['fecha_cumplidoYear']) . '-' . intval($_REQUEST['fecha_cumplidoMonth']) . '-' . intval($_REQUEST['fecha_cumplidoDay']);
	$data['fecha_cumplido'] = parseMySQLDate($data['fecha_cumplido'], '');
	$data['distancia'] = makeSafe($_REQUEST['distancia']);
		if($data['distancia'] == empty_lookup_value){ $data['distancia'] = ''; }

	// hook: planificacion_equipos_before_insert
	if(function_exists('planificacion_equipos_before_insert')){
		$args=array();
		if(!planificacion_equipos_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `planificacion_equipos` set       `planificacion`=' . (($data['planificacion'] !== '' && $data['planificacion'] !== NULL) ? "'{$data['planificacion']}'" : 'NULL') . ', `cliente`=' . (($data['cliente'] !== '' && $data['cliente'] !== NULL) ? "'{$data['cliente']}'" : 'NULL') . ', `equipo`=' . (($data['equipo'] !== '' && $data['equipo'] !== NULL) ? "'{$data['equipo']}'" : 'NULL') . ', `modelo`=' . (($data['modelo'] !== '' && $data['modelo'] !== NULL) ? "'{$data['modelo']}'" : 'NULL') . ', `ubicacion`=' . (($data['ubicacion'] !== '' && $data['ubicacion'] !== NULL) ? "'{$data['ubicacion']}'" : 'NULL') . ', `horometro`=' . (($data['horometro'] !== '' && $data['horometro'] !== NULL) ? "'{$data['horometro']}'" : 'NULL') . ', `cumplido`=' . (($data['cumplido'] !== '' && $data['cumplido'] !== NULL) ? "'{$data['cumplido']}'" : 'NULL') . ', `comentarios`=' . (($data['comentarios'] !== '' && $data['comentarios'] !== NULL) ? "'{$data['comentarios']}'" : 'NULL') . ', `fecha_cumplido`=' . (($data['fecha_cumplido'] !== '' && $data['fecha_cumplido'] !== NULL) ? "'{$data['fecha_cumplido']}'" : 'NULL') . ', `distancia`=' . (($data['distancia'] !== '' && $data['distancia'] !== NULL) ? "'{$data['distancia']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"planificacion_equipos_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: planificacion_equipos_after_insert
	if(function_exists('planificacion_equipos_after_insert')){
		$res = sql("select * from `planificacion_equipos` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!planificacion_equipos_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('planificacion_equipos', $recID, getLoggedMemberID());

	return $recID;
}

function planificacion_equipos_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('planificacion_equipos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificacion_equipos' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificacion_equipos' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: planificacion_equipos_before_delete
	if(function_exists('planificacion_equipos_before_delete')){
		$args=array();
		if(!planificacion_equipos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: planificacion_pendientes
	$res = sql("select `id` from `planificacion_equipos` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `planificacion_pendientes` where `planificacion`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_pendientes", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_pendientes", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='planificacion_equipos_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='planificacion_equipos_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `planificacion_equipos` where `id`='$selected_id'", $eo);

	// hook: planificacion_equipos_after_delete
	if(function_exists('planificacion_equipos_after_delete')){
		$args=array();
		planificacion_equipos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='planificacion_equipos' and pkValue='$selected_id'", $eo);
}

function planificacion_equipos_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('planificacion_equipos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificacion_equipos' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificacion_equipos' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['planificacion'] = makeSafe($_REQUEST['planificacion']);
		if($data['planificacion'] == empty_lookup_value){ $data['planificacion'] = ''; }
	$data['cliente'] = makeSafe($_REQUEST['cliente']);
		if($data['cliente'] == empty_lookup_value){ $data['cliente'] = ''; }
	$data['equipo'] = makeSafe($_REQUEST['equipo']);
		if($data['equipo'] == empty_lookup_value){ $data['equipo'] = ''; }
	$data['modelo'] = makeSafe($_REQUEST['equipo']);
		if($data['modelo'] == empty_lookup_value){ $data['modelo'] = ''; }
	$data['ubicacion'] = makeSafe($_REQUEST['ubicacion']);
		if($data['ubicacion'] == empty_lookup_value){ $data['ubicacion'] = ''; }
	$data['horometro'] = makeSafe($_REQUEST['horometro']);
		if($data['horometro'] == empty_lookup_value){ $data['horometro'] = ''; }
	$data['cumplido'] = makeSafe($_REQUEST['cumplido']);
		if($data['cumplido'] == empty_lookup_value){ $data['cumplido'] = ''; }
	$data['comentarios'] = makeSafe($_REQUEST['comentarios']);
		if($data['comentarios'] == empty_lookup_value){ $data['comentarios'] = ''; }
	$data['fecha_cumplido'] = intval($_REQUEST['fecha_cumplidoYear']) . '-' . intval($_REQUEST['fecha_cumplidoMonth']) . '-' . intval($_REQUEST['fecha_cumplidoDay']);
	$data['fecha_cumplido'] = parseMySQLDate($data['fecha_cumplido'], '');
	$data['distancia'] = makeSafe($_REQUEST['distancia']);
		if($data['distancia'] == empty_lookup_value){ $data['distancia'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: planificacion_equipos_before_update
	if(function_exists('planificacion_equipos_before_update')){
		$args=array();
		if(!planificacion_equipos_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `planificacion_equipos` set       `planificacion`=' . (($data['planificacion'] !== '' && $data['planificacion'] !== NULL) ? "'{$data['planificacion']}'" : 'NULL') . ', `cliente`=' . (($data['cliente'] !== '' && $data['cliente'] !== NULL) ? "'{$data['cliente']}'" : 'NULL') . ', `equipo`=' . (($data['equipo'] !== '' && $data['equipo'] !== NULL) ? "'{$data['equipo']}'" : 'NULL') . ', `modelo`=' . (($data['modelo'] !== '' && $data['modelo'] !== NULL) ? "'{$data['modelo']}'" : 'NULL') . ', `ubicacion`=' . (($data['ubicacion'] !== '' && $data['ubicacion'] !== NULL) ? "'{$data['ubicacion']}'" : 'NULL') . ', `horometro`=' . (($data['horometro'] !== '' && $data['horometro'] !== NULL) ? "'{$data['horometro']}'" : 'NULL') . ', `cumplido`=' . (($data['cumplido'] !== '' && $data['cumplido'] !== NULL) ? "'{$data['cumplido']}'" : 'NULL') . ', `comentarios`=' . (($data['comentarios'] !== '' && $data['comentarios'] !== NULL) ? "'{$data['comentarios']}'" : 'NULL') . ', `fecha_cumplido`=' . (($data['fecha_cumplido'] !== '' && $data['fecha_cumplido'] !== NULL) ? "'{$data['fecha_cumplido']}'" : 'NULL') . ', `distancia`=' . (($data['distancia'] !== '' && $data['distancia'] !== NULL) ? "'{$data['distancia']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="planificacion_equipos_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: planificacion_equipos_after_update
	if(function_exists('planificacion_equipos_after_update')){
		$res = sql("SELECT * FROM `planificacion_equipos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!planificacion_equipos_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='planificacion_equipos' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function planificacion_equipos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('planificacion_equipos');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_planificacion = thisOr(undo_magic_quotes($_REQUEST['filterer_planificacion']), '');
	$filterer_cliente = thisOr(undo_magic_quotes($_REQUEST['filterer_cliente']), '');
	$filterer_equipo = thisOr(undo_magic_quotes($_REQUEST['filterer_equipo']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: planificacion
	$combo_planificacion = new DataCombo;
	// combobox: cliente
	$combo_cliente = new DataCombo;
	// combobox: equipo
	$combo_equipo = new DataCombo;
	// combobox: fecha_cumplido
	$combo_fecha_cumplido = new DateCombo;
	$combo_fecha_cumplido->DateFormat = "mdy";
	$combo_fecha_cumplido->MinYear = 1900;
	$combo_fecha_cumplido->MaxYear = 2100;
	$combo_fecha_cumplido->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_cumplido->MonthNames = $Translation['month names'];
	$combo_fecha_cumplido->NamePrefix = 'fecha_cumplido';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificacion_equipos' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificacion_equipos' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `planificacion_equipos` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'planificacion_equipos_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_planificacion->SelectedData = $row['planificacion'];
		$combo_cliente->SelectedData = $row['cliente'];
		$combo_equipo->SelectedData = $row['equipo'];
		$combo_fecha_cumplido->DefaultDate = $row['fecha_cumplido'];
	}else{
		$combo_planificacion->SelectedData = $filterer_planificacion;
		$combo_cliente->SelectedData = $filterer_cliente;
		$combo_equipo->SelectedData = $filterer_equipo;
	}
	$combo_planificacion->HTML = '<span id="planificacion-container' . $rnd1 . '"></span><input type="hidden" name="planificacion" id="planificacion' . $rnd1 . '" value="' . html_attr($combo_planificacion->SelectedData) . '">';
	$combo_planificacion->MatchText = '<span id="planificacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="planificacion" id="planificacion' . $rnd1 . '" value="' . html_attr($combo_planificacion->SelectedData) . '">';
	$combo_cliente->HTML = '<span id="cliente-container' . $rnd1 . '"></span><input type="hidden" name="cliente" id="cliente' . $rnd1 . '" value="' . html_attr($combo_cliente->SelectedData) . '">';
	$combo_cliente->MatchText = '<span id="cliente-container-readonly' . $rnd1 . '"></span><input type="hidden" name="cliente" id="cliente' . $rnd1 . '" value="' . html_attr($combo_cliente->SelectedData) . '">';
	$combo_equipo->HTML = '<span id="equipo-container' . $rnd1 . '"></span><input type="hidden" name="equipo" id="equipo' . $rnd1 . '" value="' . html_attr($combo_equipo->SelectedData) . '">';
	$combo_equipo->MatchText = '<span id="equipo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="equipo" id="equipo' . $rnd1 . '" value="' . html_attr($combo_equipo->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_planificacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['planificacion'] : $filterer_planificacion); ?>"};
		AppGini.current_cliente__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['cliente'] : $filterer_cliente); ?>"};
		AppGini.current_equipo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['equipo'] : $filterer_equipo); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(planificacion_reload__RAND__) == 'function') planificacion_reload__RAND__();
				if(typeof(cliente_reload__RAND__) == 'function') cliente_reload__RAND__();
				if(typeof(equipo_reload__RAND__) == 'function') equipo_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function planificacion_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#planificacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_planificacion__RAND__.value, t: 'planificacion_equipos', f: 'planificacion' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="planificacion"]').val(resp.results[0].id);
							$j('[id=planificacion-container-readonly__RAND__]').html('<span id="planificacion-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=planificaciones_view_parent]').hide(); }else{ $j('.btn[id=planificaciones_view_parent]').show(); }


							if(typeof(planificacion_update_autofills__RAND__) == 'function') planificacion_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'planificacion_equipos', f: 'planificacion' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_planificacion__RAND__.value = e.added.id;
				AppGini.current_planificacion__RAND__.text = e.added.text;
				$j('[name="planificacion"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=planificaciones_view_parent]').hide(); }else{ $j('.btn[id=planificaciones_view_parent]').show(); }


				if(typeof(planificacion_update_autofills__RAND__) == 'function') planificacion_update_autofills__RAND__();
			});

			if(!$j("#planificacion-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_planificacion__RAND__.value, t: 'planificacion_equipos', f: 'planificacion' },
					success: function(resp){
						$j('[name="planificacion"]').val(resp.results[0].id);
						$j('[id=planificacion-container-readonly__RAND__]').html('<span id="planificacion-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=planificaciones_view_parent]').hide(); }else{ $j('.btn[id=planificaciones_view_parent]').show(); }

						if(typeof(planificacion_update_autofills__RAND__) == 'function') planificacion_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_planificacion__RAND__.value, t: 'planificacion_equipos', f: 'planificacion' },
				success: function(resp){
					$j('[id=planificacion-container__RAND__], [id=planificacion-container-readonly__RAND__]').html('<span id="planificacion-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=planificaciones_view_parent]').hide(); }else{ $j('.btn[id=planificaciones_view_parent]').show(); }

					if(typeof(planificacion_update_autofills__RAND__) == 'function') planificacion_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function cliente_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#cliente-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_cliente__RAND__.value, t: 'planificacion_equipos', f: 'cliente' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="cliente"]').val(resp.results[0].id);
							$j('[id=cliente-container-readonly__RAND__]').html('<span id="cliente-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=clientes_view_parent]').hide(); }else{ $j('.btn[id=clientes_view_parent]').show(); }


							if(typeof(cliente_update_autofills__RAND__) == 'function') cliente_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'planificacion_equipos', f: 'cliente' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_cliente__RAND__.value = e.added.id;
				AppGini.current_cliente__RAND__.text = e.added.text;
				$j('[name="cliente"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=clientes_view_parent]').hide(); }else{ $j('.btn[id=clientes_view_parent]').show(); }


				if(typeof(cliente_update_autofills__RAND__) == 'function') cliente_update_autofills__RAND__();
			});

			if(!$j("#cliente-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_cliente__RAND__.value, t: 'planificacion_equipos', f: 'cliente' },
					success: function(resp){
						$j('[name="cliente"]').val(resp.results[0].id);
						$j('[id=cliente-container-readonly__RAND__]').html('<span id="cliente-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=clientes_view_parent]').hide(); }else{ $j('.btn[id=clientes_view_parent]').show(); }

						if(typeof(cliente_update_autofills__RAND__) == 'function') cliente_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_cliente__RAND__.value, t: 'planificacion_equipos', f: 'cliente' },
				success: function(resp){
					$j('[id=cliente-container__RAND__], [id=cliente-container-readonly__RAND__]').html('<span id="cliente-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=clientes_view_parent]').hide(); }else{ $j('.btn[id=clientes_view_parent]').show(); }

					if(typeof(cliente_update_autofills__RAND__) == 'function') cliente_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function equipo_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#equipo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_equipo__RAND__.value, t: 'planificacion_equipos', f: 'equipo' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="equipo"]').val(resp.results[0].id);
							$j('[id=equipo-container-readonly__RAND__]').html('<span id="equipo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=equipos_view_parent]').hide(); }else{ $j('.btn[id=equipos_view_parent]').show(); }


							if(typeof(equipo_update_autofills__RAND__) == 'function') equipo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'planificacion_equipos', f: 'equipo' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_equipo__RAND__.value = e.added.id;
				AppGini.current_equipo__RAND__.text = e.added.text;
				$j('[name="equipo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=equipos_view_parent]').hide(); }else{ $j('.btn[id=equipos_view_parent]').show(); }


				if(typeof(equipo_update_autofills__RAND__) == 'function') equipo_update_autofills__RAND__();
			});

			if(!$j("#equipo-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_equipo__RAND__.value, t: 'planificacion_equipos', f: 'equipo' },
					success: function(resp){
						$j('[name="equipo"]').val(resp.results[0].id);
						$j('[id=equipo-container-readonly__RAND__]').html('<span id="equipo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=equipos_view_parent]').hide(); }else{ $j('.btn[id=equipos_view_parent]').show(); }

						if(typeof(equipo_update_autofills__RAND__) == 'function') equipo_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_equipo__RAND__.value, t: 'planificacion_equipos', f: 'equipo' },
				success: function(resp){
					$j('[id=equipo-container__RAND__], [id=equipo-container-readonly__RAND__]').html('<span id="equipo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=equipos_view_parent]').hide(); }else{ $j('.btn[id=equipos_view_parent]').show(); }

					if(typeof(equipo_update_autofills__RAND__) == 'function') equipo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/planificacion_equipos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/planificacion_equipos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Planificacion equipo details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return planificacion_equipos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return planificacion_equipos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return planificacion_equipos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#planificacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#planificacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#cliente').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#cliente_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#equipo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#equipo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#ubicacion').replaceWith('<div class=\"form-control-static\" id=\"ubicacion\">' + (jQuery('#ubicacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#horometro').replaceWith('<div class=\"form-control-static\" id=\"horometro\">' + (jQuery('#horometro').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#cumplido').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#comentarios').replaceWith('<div class=\"form-control-static\" id=\"comentarios\">' + (jQuery('#comentarios').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fecha_cumplido').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fecha_cumplidoDay, #fecha_cumplidoMonth, #fecha_cumplidoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#distancia').replaceWith('<div class=\"form-control-static\" id=\"distancia\">' + (jQuery('#distancia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(planificacion)%%>', $combo_planificacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(planificacion)%%>', $combo_planificacion->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(planificacion)%%>', urlencode($combo_planificacion->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(cliente)%%>', $combo_cliente->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(cliente)%%>', $combo_cliente->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(cliente)%%>', urlencode($combo_cliente->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(equipo)%%>', $combo_equipo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(equipo)%%>', $combo_equipo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(equipo)%%>', urlencode($combo_equipo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(fecha_cumplido)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fecha_cumplido->GetHTML(true) . '</div>' : $combo_fecha_cumplido->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_cumplido)%%>', $combo_fecha_cumplido->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'planificacion' => array('planificaciones', 'Planificacion'), 'cliente' => array('clientes', 'Cliente'), 'equipo' => array('equipos', 'Equipo'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(planificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cliente)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(equipo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ubicacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(horometro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cumplido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comentarios)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_cumplido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(distancia)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(planificacion)%%>', safe_html($urow['planificacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(planificacion)%%>', html_attr($row['planificacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(planificacion)%%>', urlencode($urow['planificacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cliente)%%>', safe_html($urow['cliente']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cliente)%%>', html_attr($row['cliente']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente)%%>', urlencode($urow['cliente']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(equipo)%%>', safe_html($urow['equipo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(equipo)%%>', html_attr($row['equipo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equipo)%%>', urlencode($urow['equipo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ubicacion)%%>', safe_html($urow['ubicacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ubicacion)%%>', html_attr($row['ubicacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ubicacion)%%>', urlencode($urow['ubicacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(horometro)%%>', safe_html($urow['horometro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(horometro)%%>', html_attr($row['horometro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(horometro)%%>', urlencode($urow['horometro']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(cumplido)%%>', ($row['cumplido'] ? "checked" : ""), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(comentarios)%%>', safe_html($urow['comentarios']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(comentarios)%%>', html_attr($row['comentarios']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comentarios)%%>', urlencode($urow['comentarios']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cumplido)%%>', @date('m/d/Y', @strtotime(html_attr($row['fecha_cumplido']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cumplido)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['fecha_cumplido'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(distancia)%%>', safe_html($urow['distancia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(distancia)%%>', html_attr($row['distancia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(distancia)%%>', urlencode($urow['distancia']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(planificacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(planificacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cliente)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cliente)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(equipo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equipo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ubicacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ubicacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(horometro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(horometro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(cumplido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(comentarios)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comentarios)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_cumplido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_cumplido)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(distancia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(distancia)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tequipo_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'planificacion_equipos_autofill.php?rnd1=$rnd1&mfk=equipo&id=' + encodeURIComponent('".addslashes($row['equipo'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'planificacion_equipos_autofill.php?rnd1=$rnd1&mfk=equipo&id=' + encodeURIComponent(AppGini.current_equipo{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#equipo$rnd1').prop('disabled', true); \$j('#equipoLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#equipo$rnd1').prop('disabled', false); " : "\$j('#equipo$rnd1').prop('disabled', true); ")."\$j('#equipoLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#equipo_caption').length) \$j('#equipo_caption').click(function(){ /* */ equipo_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('planificacion_equipos');
	if($selected_id){
		$jdata = get_joined_record('planificacion_equipos', $selected_id);
		if($jdata === false) $jdata = get_defaults('planificacion_equipos');
		$rdata = $row;
	}
	$templateCode .= loadView('planificacion_equipos-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: planificacion_equipos_dv
	if(function_exists('planificacion_equipos_dv')){
		$args=array();
		planificacion_equipos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>