<?php

// Data functions (insert, update, delete, form) for table planificaciones

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function planificaciones_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('planificaciones');
	if(!$arrPerm[1]){
		return false;
	}

	$data['titulo'] = makeSafe($_REQUEST['titulo']);
		if($data['titulo'] == empty_lookup_value){ $data['titulo'] = ''; }
	$data['tecnico'] = makeSafe($_REQUEST['tecnico']);
		if($data['tecnico'] == empty_lookup_value){ $data['tecnico'] = ''; }
	$data['camioneta'] = makeSafe($_REQUEST['camioneta']);
		if($data['camioneta'] == empty_lookup_value){ $data['camioneta'] = ''; }
	$data['fecha_planificado'] = intval($_REQUEST['fecha_planificadoYear']) . '-' . intval($_REQUEST['fecha_planificadoMonth']) . '-' . intval($_REQUEST['fecha_planificadoDay']);
	$data['fecha_planificado'] = parseMySQLDate($data['fecha_planificado'], '');

	// hook: planificaciones_before_insert
	if(function_exists('planificaciones_before_insert')){
		$args=array();
		if(!planificaciones_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `planificaciones` set       `titulo`=' . (($data['titulo'] !== '' && $data['titulo'] !== NULL) ? "'{$data['titulo']}'" : 'NULL') . ', `tecnico`=' . (($data['tecnico'] !== '' && $data['tecnico'] !== NULL) ? "'{$data['tecnico']}'" : 'NULL') . ', `camioneta`=' . (($data['camioneta'] !== '' && $data['camioneta'] !== NULL) ? "'{$data['camioneta']}'" : 'NULL') . ', `fecha_planificado`=' . (($data['fecha_planificado'] !== '' && $data['fecha_planificado'] !== NULL) ? "'{$data['fecha_planificado']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"planificaciones_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: planificaciones_after_insert
	if(function_exists('planificaciones_after_insert')){
		$res = sql("select * from `planificaciones` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!planificaciones_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('planificaciones', $recID, getLoggedMemberID());

	return $recID;
}

function planificaciones_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('planificaciones');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificaciones' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificaciones' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: planificaciones_before_delete
	if(function_exists('planificaciones_before_delete')){
		$args=array();
		if(!planificaciones_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: planificacion_equipos
	$res = sql("select `id` from `planificaciones` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `planificacion_equipos` where `planificacion`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_equipos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "planificacion_equipos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='planificaciones_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='planificaciones_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `planificaciones` where `id`='$selected_id'", $eo);

	// hook: planificaciones_after_delete
	if(function_exists('planificaciones_after_delete')){
		$args=array();
		planificaciones_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='planificaciones' and pkValue='$selected_id'", $eo);
}

function planificaciones_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('planificaciones');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificaciones' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificaciones' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['titulo'] = makeSafe($_REQUEST['titulo']);
		if($data['titulo'] == empty_lookup_value){ $data['titulo'] = ''; }
	$data['tecnico'] = makeSafe($_REQUEST['tecnico']);
		if($data['tecnico'] == empty_lookup_value){ $data['tecnico'] = ''; }
	$data['camioneta'] = makeSafe($_REQUEST['camioneta']);
		if($data['camioneta'] == empty_lookup_value){ $data['camioneta'] = ''; }
	$data['fecha_planificado'] = intval($_REQUEST['fecha_planificadoYear']) . '-' . intval($_REQUEST['fecha_planificadoMonth']) . '-' . intval($_REQUEST['fecha_planificadoDay']);
	$data['fecha_planificado'] = parseMySQLDate($data['fecha_planificado'], '');
	$data['selectedID']=makeSafe($selected_id);

	// hook: planificaciones_before_update
	if(function_exists('planificaciones_before_update')){
		$args=array();
		if(!planificaciones_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `planificaciones` set       `titulo`=' . (($data['titulo'] !== '' && $data['titulo'] !== NULL) ? "'{$data['titulo']}'" : 'NULL') . ', `tecnico`=' . (($data['tecnico'] !== '' && $data['tecnico'] !== NULL) ? "'{$data['tecnico']}'" : 'NULL') . ', `camioneta`=' . (($data['camioneta'] !== '' && $data['camioneta'] !== NULL) ? "'{$data['camioneta']}'" : 'NULL') . ', `fecha_planificado`=' . (($data['fecha_planificado'] !== '' && $data['fecha_planificado'] !== NULL) ? "'{$data['fecha_planificado']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="planificaciones_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: planificaciones_after_update
	if(function_exists('planificaciones_after_update')){
		$res = sql("SELECT * FROM `planificaciones` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!planificaciones_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='planificaciones' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function planificaciones_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('planificaciones');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_tecnico = thisOr(undo_magic_quotes($_REQUEST['filterer_tecnico']), '');
	$filterer_camioneta = thisOr(undo_magic_quotes($_REQUEST['filterer_camioneta']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: tecnico
	$combo_tecnico = new DataCombo;
	// combobox: camioneta
	$combo_camioneta = new DataCombo;
	// combobox: fecha_planificado
	$combo_fecha_planificado = new DateCombo;
	$combo_fecha_planificado->DateFormat = "mdy";
	$combo_fecha_planificado->MinYear = 1900;
	$combo_fecha_planificado->MaxYear = 2100;
	$combo_fecha_planificado->DefaultDate = parseMySQLDate('', '');
	$combo_fecha_planificado->MonthNames = $Translation['month names'];
	$combo_fecha_planificado->NamePrefix = 'fecha_planificado';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='planificaciones' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='planificaciones' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `planificaciones` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'planificaciones_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_tecnico->SelectedData = $row['tecnico'];
		$combo_camioneta->SelectedData = $row['camioneta'];
		$combo_fecha_planificado->DefaultDate = $row['fecha_planificado'];
	}else{
		$combo_tecnico->SelectedData = $filterer_tecnico;
		$combo_camioneta->SelectedData = $filterer_camioneta;
	}
	$combo_tecnico->HTML = '<span id="tecnico-container' . $rnd1 . '"></span><input type="hidden" name="tecnico" id="tecnico' . $rnd1 . '" value="' . html_attr($combo_tecnico->SelectedData) . '">';
	$combo_tecnico->MatchText = '<span id="tecnico-container-readonly' . $rnd1 . '"></span><input type="hidden" name="tecnico" id="tecnico' . $rnd1 . '" value="' . html_attr($combo_tecnico->SelectedData) . '">';
	$combo_camioneta->HTML = '<span id="camioneta-container' . $rnd1 . '"></span><input type="hidden" name="camioneta" id="camioneta' . $rnd1 . '" value="' . html_attr($combo_camioneta->SelectedData) . '">';
	$combo_camioneta->MatchText = '<span id="camioneta-container-readonly' . $rnd1 . '"></span><input type="hidden" name="camioneta" id="camioneta' . $rnd1 . '" value="' . html_attr($combo_camioneta->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_tecnico__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['tecnico'] : $filterer_tecnico); ?>"};
		AppGini.current_camioneta__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['camioneta'] : $filterer_camioneta); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(tecnico_reload__RAND__) == 'function') tecnico_reload__RAND__();
				if(typeof(camioneta_reload__RAND__) == 'function') camioneta_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function tecnico_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#tecnico-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_tecnico__RAND__.value, t: 'planificaciones', f: 'tecnico' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="tecnico"]').val(resp.results[0].id);
							$j('[id=tecnico-container-readonly__RAND__]').html('<span id="tecnico-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tecnicos_view_parent]').hide(); }else{ $j('.btn[id=tecnicos_view_parent]').show(); }


							if(typeof(tecnico_update_autofills__RAND__) == 'function') tecnico_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'planificaciones', f: 'tecnico' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_tecnico__RAND__.value = e.added.id;
				AppGini.current_tecnico__RAND__.text = e.added.text;
				$j('[name="tecnico"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tecnicos_view_parent]').hide(); }else{ $j('.btn[id=tecnicos_view_parent]').show(); }


				if(typeof(tecnico_update_autofills__RAND__) == 'function') tecnico_update_autofills__RAND__();
			});

			if(!$j("#tecnico-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_tecnico__RAND__.value, t: 'planificaciones', f: 'tecnico' },
					success: function(resp){
						$j('[name="tecnico"]').val(resp.results[0].id);
						$j('[id=tecnico-container-readonly__RAND__]').html('<span id="tecnico-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tecnicos_view_parent]').hide(); }else{ $j('.btn[id=tecnicos_view_parent]').show(); }

						if(typeof(tecnico_update_autofills__RAND__) == 'function') tecnico_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_tecnico__RAND__.value, t: 'planificaciones', f: 'tecnico' },
				success: function(resp){
					$j('[id=tecnico-container__RAND__], [id=tecnico-container-readonly__RAND__]').html('<span id="tecnico-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tecnicos_view_parent]').hide(); }else{ $j('.btn[id=tecnicos_view_parent]').show(); }

					if(typeof(tecnico_update_autofills__RAND__) == 'function') tecnico_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function camioneta_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#camioneta-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_camioneta__RAND__.value, t: 'planificaciones', f: 'camioneta' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="camioneta"]').val(resp.results[0].id);
							$j('[id=camioneta-container-readonly__RAND__]').html('<span id="camioneta-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=camionetas_view_parent]').hide(); }else{ $j('.btn[id=camionetas_view_parent]').show(); }


							if(typeof(camioneta_update_autofills__RAND__) == 'function') camioneta_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'planificaciones', f: 'camioneta' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_camioneta__RAND__.value = e.added.id;
				AppGini.current_camioneta__RAND__.text = e.added.text;
				$j('[name="camioneta"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=camionetas_view_parent]').hide(); }else{ $j('.btn[id=camionetas_view_parent]').show(); }


				if(typeof(camioneta_update_autofills__RAND__) == 'function') camioneta_update_autofills__RAND__();
			});

			if(!$j("#camioneta-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_camioneta__RAND__.value, t: 'planificaciones', f: 'camioneta' },
					success: function(resp){
						$j('[name="camioneta"]').val(resp.results[0].id);
						$j('[id=camioneta-container-readonly__RAND__]').html('<span id="camioneta-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=camionetas_view_parent]').hide(); }else{ $j('.btn[id=camionetas_view_parent]').show(); }

						if(typeof(camioneta_update_autofills__RAND__) == 'function') camioneta_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_camioneta__RAND__.value, t: 'planificaciones', f: 'camioneta' },
				success: function(resp){
					$j('[id=camioneta-container__RAND__], [id=camioneta-container-readonly__RAND__]').html('<span id="camioneta-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=camionetas_view_parent]').hide(); }else{ $j('.btn[id=camionetas_view_parent]').show(); }

					if(typeof(camioneta_update_autofills__RAND__) == 'function') camioneta_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/planificaciones_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/planificaciones_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Planificacione details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return planificaciones_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return planificaciones_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return planificaciones_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#titulo').replaceWith('<div class=\"form-control-static\" id=\"titulo\">' + (jQuery('#titulo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#tecnico').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#tecnico_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#camioneta').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#camioneta_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#fecha_planificado').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fecha_planificadoDay, #fecha_planificadoMonth, #fecha_planificadoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(tecnico)%%>', $combo_tecnico->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tecnico)%%>', $combo_tecnico->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(tecnico)%%>', urlencode($combo_tecnico->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(camioneta)%%>', $combo_camioneta->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(camioneta)%%>', $combo_camioneta->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(camioneta)%%>', urlencode($combo_camioneta->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(fecha_planificado)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fecha_planificado->GetHTML(true) . '</div>' : $combo_fecha_planificado->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha_planificado)%%>', $combo_fecha_planificado->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'tecnico' => array('tecnicos', 'Tecnico'), 'camioneta' => array('camionetas', 'Camioneta'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(titulo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tecnico)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(camioneta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_planificado)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(titulo)%%>', safe_html($urow['titulo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(titulo)%%>', html_attr($row['titulo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(titulo)%%>', urlencode($urow['titulo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tecnico)%%>', safe_html($urow['tecnico']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tecnico)%%>', html_attr($row['tecnico']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tecnico)%%>', urlencode($urow['tecnico']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(camioneta)%%>', safe_html($urow['camioneta']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(camioneta)%%>', html_attr($row['camioneta']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(camioneta)%%>', urlencode($urow['camioneta']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_planificado)%%>', @date('m/d/Y', @strtotime(html_attr($row['fecha_planificado']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_planificado)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['fecha_planificado'])))), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(titulo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(titulo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tecnico)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tecnico)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(camioneta)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(camioneta)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_planificado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_planificado)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('planificaciones');
	if($selected_id){
		$jdata = get_joined_record('planificaciones', $selected_id);
		if($jdata === false) $jdata = get_defaults('planificaciones');
		$rdata = $row;
	}
	$templateCode .= loadView('planificaciones-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: planificaciones_dv
	if(function_exists('planificaciones_dv')){
		$args=array();
		planificaciones_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>